[env:esp01]
platform = espressif8266
board = esp01_1m
framework = arduino

monitor_speed = 115200

lib_deps =
    ESP8266Ping

build_flags =
    -DSERIAL_RX_BUFFER_SIZE=1024
    -DSERIAL_TX_BUFFER_SIZE=1024
